# Variables
@host = http://localhost:3002
@version= v1
@controller= postcodes
@accept = application/json

### List
GET {{host}}/{{version}}/{{controller}} HTTP/1.1
Accept: {{accept}}

### Get
GET {{host}}/{{version}}/{{controller}}/1060 HTTP/1.1
Accept: {{accept}}

### Total Count
GET {{host}}/{{version}}/{{controller}}/totaal-aantal HTTP/1.1
Accept: {{accept}}
