# Variables

# @host = http://localhost:2080
@host = https://api.basisregisters.dev-vlaanderen.be
# @host = https://api.basisregisters.staging-vlaanderen.be
# @host = https://api.basisregisters.vlaanderen.be
@version = v1
@accept = application/json
@service= postinfo

### List
GET {{host}}/{{version}}/{{service}} HTTP/1.1
Accept: {{accept}}

### Get
GET {{host}}/{{version}}/{{service}}/1060 HTTP/1.1
Accept: {{accept}}

### Total count
GET {{host}}/{{version}}/{{service}}/totaal-aantal HTTP/1.1
Accept: {{accept}}
